---
apiVersion: v1
kind: Service
metadata:
  name: ingestion-service
  namespace: flowfish-local
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
      name: grpc
  selector:
    app: ingestion-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingestion-service
  namespace: flowfish-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ingestion-service
  template:
    metadata:
      labels:
        app: ingestion-service
    spec:
      containers:
        - name: ingestion-service
          image: taylanbakircioglu/flowfish:ingestion-service-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: SERVICE_NAME
              value: ingestion-service
            - name: GRPC_PORT
              value: "5000"
            - name: LOG_LEVEL
              value: INFO
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: flowfish
            - name: RABBITMQ_PASSWORD
              value: flowfish123
            - name: CLUSTER_MANAGER_URL
              value: cluster-manager:5001
            - name: GADGET_PROTOCOL
              value: kubectl
            - name: GADGET_NAMESPACE
              value: flowfish-local
            - name: GADGET_REGISTRY
              value: ""
            - name: GADGET_IMAGE_VERSION
              value: v0.48.0
            - name: GADGET_IMAGE_PREFIX
              value: ""
            - name: FLOWFISH_ENCRYPTION_KEY
              value: Zo6CfvKB6y4IIPMAUJermGJ7UQm8wgjnvuehRGKY-sA=
          readinessProbe:
            exec:
              command:
                - python
                - -c
                - "import grpc; ch=grpc.insecure_channel('localhost:5000'); ch.close()"
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - python
                - -c
                - "import grpc; ch=grpc.insecure_channel('localhost:5000'); ch.close()"
            initialDelaySeconds: 15
            periodSeconds: 10
