---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: flowfish
  namespace: {{OPENSHIFT_NAMESPACE}}
  labels:
    app: flowfish

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: flowfish
  namespace: {{OPENSHIFT_NAMESPACE}}
  labels:
    app: flowfish
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/portforward", "pods/exec", "pods/log"]
    verbs: ["create", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets", "daemonsets"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: flowfish
  namespace: {{OPENSHIFT_NAMESPACE}}
  labels:
    app: flowfish
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: flowfish
subjects:
  - kind: ServiceAccount
    name: flowfish
    namespace: {{OPENSHIFT_NAMESPACE}}
